version: '3'

services:
  ggosunnaefriends:
    image: ggosunnaefriends
    build: .
    ports:
      - "8888:8888"
    networks:
      - redis-network
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_ACCESS_EXP=${JWT_ACCESS_EXP}
      - JWT_REFRESH_EXP=${JWT_REFRESH_EXP}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FILE_PATH=${FILE_PATH}
      - REST_API_KEY=${REST_API_KEY}
    volumes:
      - "/home/ubuntu/Tarun/image:/home/ubuntu/Tarun/image"
  redis:
    image: redis
    container_name: redis-server
    ports:
        - "6379:6379"
    networks:
        - redis-network
networks:
  redis-network:
