version: 0.2

phases:   # github action의 jobs와 비슷한 의미
  build:
    commands:   # build 라는 작업 실행 시 실행될 shell 명령어들
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar) 
      - pwd

artifacts:    # artifact 설정
  files:      # appspec 파일 설정, 어떤 파일을 가져갈지 선택
    - appspec.yml
    - build/libs/*.jar
    - scripts/**
  discard-paths: yes  # CodeBuild의 결과물에 해당 파일들을 추가한다.

cache:
  paths:
    - '/root/.gradle/caches/**/*' # 캐싱된 위치