spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6380}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# 내부 포트 설정
server:
  port: 8888

auth:
  jwt:
    secret: ${JWT_SECRET:asdf1234}
    exp:
      access: ${JWT_ACCESS_EXP:12345}
      refresh: ${JWT_REFRESH_EXP:2345678}

file:
  path: ${FILE_PATH}

kakao:
  api-key: ${REST_API_KEY}